server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.157.128:8848
    gateway:
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/message/**,/session/**

        - id: character-service
          uri: lb://character-service
          predicates:
            - Path=/character/**

        - id: memory-service
          uri: lb://memory-service
          predicates:
            - Path=/memory/**

        - id: girlfriend-service
          uri: lb://girlfriend-service
          predicates:
            - Path=/ai/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "Authorization, Content-Type"
            allowedMethods: # 明确允许的HTTP方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS  # 允许预检请求
aigirlfriend:
  auth:
    excludePaths:
      - /user/login
      - /user/register
